### ISSUE TITLE
Local development: no model-oauth

### ISSUE THREAD

**Issue by durapensa** [bpowers/simlin#28]
README.md refers to a step `. ~/model-oauth` to set environment variables, however that file resides outside of the git repo.

Could that be the cause of `yarn start-frontend` failing with `Module not found: Can't resolve './core/engine' in '/home/durapensa/simlin/src/engine`

**Comment by bpowers** [comment]
hi @durapensa  - this is done now, you shouldn't need any external files to run model locally.  Cheers - LMK if you need anything else or have suggestions
