### ISSUE TITLE
Constantly dragging elements on Firefox

### ISSUE THREAD

**Issue by i-need-to-tell-you-something** [bpowers/simlin#64]
When clicking on any element of a model, it behaves as if I pressed down to select it and I cannot release the selection - i.e. the element will follow the cursor around as if I wanted to drag it. This continues until I click on another element.

Observed on Firefox 95.0.1 (64-bit) on Linux
It seemed fine on Chromium 95.0.4638.69

**Comment by bpowers** [comment]
thanks for finding this @i-need-to-tell-you-something ! I can reproduce and will work on a fix shortly.

**Comment by bpowers** [comment]
sorry for the delay here @i-need-to-tell-you-something -- this is fixed in cdaecdd5af445dc25952a222a7e5c3b321625b95 and I've deployed https://app.simlin.com with the fix.

**Comment by i-need-to-tell-you-something** [comment]
Awesome. Thanks!
Considering many projects I've seen, this was much more than a satisfactory turnaround time. :smile:
