### ISSUE TITLE
Change curve of arrow?

### ISSUE THREAD

**Issue by travisfranck** [bpowers/simlin#87]
Question:  How does a modeler change the curve of an arrow or make a straight arrow?  The Logistics model has straight arrows, but I couldn't figure out how to draw them.  The Link tool only drew one arc type (I think clockwise arc).

**Comment by bpowers** [comment]
@travisfranck you click anywhere on the arc of a connector and drag to change the curve (or make it a straight line).  Not super discoverable - I'll think about how to improve that

**Comment by travisfranck** [comment]
Confirming this works for me.  I guess I tried clicking the arrow head to see if it would rotate around the variable (change where it connects) but the arc makes sense too.
